let randomEmoji1 = "😎".codePointAt(0);
let randomEmoji2 = "😄".codePointAt(0);
let randomEmoji3 = '🤘'.codePointAt(0);
let randomEmoji4 = "😆".codePointAt(0);
let randomEmoji5 = "👍".codePointAt(0)
console.log(randomEmoji1.toString(2)+", "+randomEmoji1.toString(8)+", "+randomEmoji1.toString(10)+", "+randomEmoji1.toString(16));
console.log(randomEmoji2.toString(2)+", "+randomEmoji2.toString(8)+", "+randomEmoji2.toString(10)+", "+randomEmoji2.toString(16));
console.log(randomEmoji3.toString(2)+", "+randomEmoji3.toString(8)+", "+randomEmoji3.toString(10)+", "+randomEmoji3.toString(16));
console.log(randomEmoji4.toString(2)+", "+randomEmoji4.toString(8)+", "+randomEmoji4.toString(10)+", "+randomEmoji4.toString(16));
console.log(randomEmoji5.toString(2)+", "+randomEmoji5.toString(8)+", "+randomEmoji5.toString(10)+", "+randomEmoji5.toString(16));