let a = 1;
let b = 2;
let c = 3;
let d = 4;
let e = 5;
let f = 6;
let g = 7;
let h = 8;
let i = 9;
let j = 10;
(a % 2 === 1) && console.log (a);
(b % 2 === 1) && console.log (b);
(c % 2 === 1) && console.log (c);
(d % 2 === 1) && console.log (d);
(e % 2 === 1) && console.log (e);
(f % 2 === 1) && console.log (f);
//(g % 2 === 1) && console.log (g);
(h % 2 === 1) && console.log (h);
//(i % 2 === 1) && console.log (i);
(j % 2 === 1) && console.log (j);